# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/matcher.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/matcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/matcher.proto\x12\tipmatcher\".\n\x0eHostSubnetPair\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0e\n\x06subnet\x18\x02 \x01(\t\"!\n\x0cMatchRequest\x12\x11\n\taddresses\x18\x01 \x03(\t\";\n\rMatchResponse\x12*\n\x07matches\x18\x01 \x03(\x0b\x32\x19.ipmatcher.HostSubnetPairb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.matcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOSTSUBNETPAIR']._serialized_start=34
  _globals['_HOSTSUBNETPAIR']._serialized_end=80
  _globals['_MATCHREQUEST']._serialized_start=82
  _globals['_MATCHREQUEST']._serialized_end=115
  _globals['_MATCHRESPONSE']._serialized_start=117
  _globals['_MATCHRESPONSE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
